//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module test(

    //////////// ADC //////////
    output                          ADC_CONVST,
    output                          ADC_DIN,
    input                           ADC_DOUT,
    output                          ADC_SCLK,

    //////////// Audio //////////
    input                           AUD_ADCDAT,
    inout                           AUD_ADCLRCK,
    inout                           AUD_BCLK,
    output                          AUD_DACDAT,
    inout                           AUD_DACLRCK,
    output                          AUD_XCK,

    //////////// CLOCK //////////
    input                           CLOCK2_50,
    input                           CLOCK3_50,
    input                           CLOCK4_50,
    input                           CLOCK_50,

    //////////// SDRAM //////////
    output            [12:0]        DRAM_ADDR,
    output             [1:0]        DRAM_BA,
    output                          DRAM_CAS_N,
    output                          DRAM_CKE,
    output                          DRAM_CLK,
    output                          DRAM_CS_N,
    inout             [15:0]        DRAM_DQ,
    output                          DRAM_LDQM,
    output                          DRAM_RAS_N,
    output                          DRAM_UDQM,
    output                          DRAM_WE_N,

    //////////// I2C for Audio and Video-In //////////
    output                          FPGA_I2C_SCLK,
    inout                           FPGA_I2C_SDAT,

    //////////// SEG7 //////////
    output             [6:0]        HEX0,
    output             [6:0]        HEX1,
    output             [6:0]        HEX2,
    output             [6:0]        HEX3,
    output             [6:0]        HEX4,
    output             [6:0]        HEX5,

    //////////// IR //////////
    input                           IRDA_RXD,
    output                          IRDA_TXD,

    //////////// KEY //////////
    input              [3:0]        KEY,

    //////////// LED //////////
    output             [9:0]        LEDR,

    //////////// PS2 //////////
    inout                           PS2_CLK,
    inout                           PS2_CLK2,
    inout                           PS2_DAT,
    inout                           PS2_DAT2,

    //////////// SW //////////
    input              [9:0]        SW,

    //////////// Video-In //////////
    input                           TD_CLK27,
    input              [7:0]        TD_DATA,
    input                           TD_HS,
    output                          TD_RESET_N,
    input                           TD_VS,

    //////////// VGA //////////
    output                          VGA_BLANK_N,
    output             [7:0]        VGA_B,
    output                          VGA_CLK,
    output             [7:0]        VGA_G,
    output                          VGA_HS,
    output             [7:0]        VGA_R,
    output                          VGA_SYNC_N,
    output                          VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

    reg [31:0] count; 

//=======================================================
//  Structural coding
//=======================================================

    // Simple Counter Implementation
    // Uses CLOCK_50 (50MHz oscillator)
    // Uses KEY[0] as active-low Reset
    always @(posedge CLOCK_50 or negedge KEY[0]) begin
        if (~KEY[0]) begin
            count <= 32'b0;
        end else begin
            count <= count + 1;
        end
    end

    // Assign the upper bits of the counter to the LEDs.
    // 50MHz clock = 20ns period.
    // Bit 23 toggles roughly every 0.16 seconds (~3Hz).
    // Using bits [31:22] ensures the blinking is visible to the human eye.
    assign LEDR = count[31:22];

    // Turn off 7-segment displays (active low)
    assign HEX0 = 7'h7F;
    assign HEX1 = 7'h7F;
    assign HEX2 = 7'h7F;
    assign HEX3 = 7'h7F;
    assign HEX4 = 7'h7F;
    assign HEX5 = 7'h7F;

endmodule